name: Deploy Next.js to Google Cloud Run

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-ebfab141-8521-41e8-ae1
  REGION: europe-west1
  REPOSITORY: mon-repo-docker
  SERVICE_NAME: qi-front-app
  WORKLOAD_IDENTITY_PROVIDER: 'projects/377621436332/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  SERVICE_ACCOUNT: 'github-actions-sa@project-ebfab141-8521-41e8-ae1.iam.gserviceaccount.com'

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

          docker build \
            --build-arg NEXT_PUBLIC_SSO_URL="https://sso-front-mp3dhl7baq-ew.a.run.app" \
            --build-arg NEXT_PUBLIC_SSO_API_URL="https://qavaa-innovate-sso-zlvwvifuvq-ew.a.run.app" \
            --build-arg NEXT_PUBLIC_SSO_CLIENT_ID="o22CDMr2DsKgTAtuB437S90eLvB1KgPUbBeRYsYX" \
            --build-arg NEXT_PUBLIC_SSO_REDIRECT_URI="https://qi-front-app-l2tbnetuqa-ew.a.run.app/api/auth/callback" \
            --build-arg NEXT_PUBLIC_API_BASE_URL="https://contents-lab-api-5jbnazjbya-ew.a.run.app/api" \
            -t $IMAGE_TAG .

          docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: '--port=8080'
          env_vars: |
            SSO_CLIENT_ID=o22CDMr2DsKgTAtuB437S90eLvB1KgPUbBeRYsYX
            SSO_CLIENT_SECRET=${{ secrets.SSO_CLIENT_SECRET }}
            REDIRECT_URI=https://qi-front-app-l2tbnetuqa-ew.a.run.app/api/auth/callback
            NEXT_PUBLIC_SSO_URL=https://sso-front-mp3dhl7baq-ew.a.run.app

      - name: Show Service URL
        run: |
          echo "Déploiement réussi !"
          echo "URL du service : ${{ steps.deploy.outputs.url }}"
